services:
  device_backup:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      LOGFILE: /logs/logfile.log
    networks:
      - network_app
    volumes:
      - /var/network_backup_app/backups:/network_backups
      - /var/network_backup_app/logs:/logs

networks:
  network_app:
    driver: bridge


