services:
  device_backup:
    build:
      dockerfile: docker/Dockerfile
    environment:
      LOGFILE: logfile.log
    networks:
      - host
    volumes:
      - /var/network_backup_app:/app

networks:
  host:
    name: host
    external: true


